src/main/java/com/playground/api/vote/controller/VoteController.java, src/main/java/com/playground/api/vote/entity/QestnAnswerEntity.java, src/main/java/com/playground/api/vote/entity/QestnEntity.java, src/main/java/com/playground/api/vote/entity/VoteEntity.java, src/main/java/com/playground/api/vote/entity/VoteIemEntity.java
create entity of Vote and check the push
=> Vote Api - test entity commit

src/main/java/com/playground/api/vote/controller/VoteController.java, src/main/java/com/playground/api/vote/entity/QestnAnswerEntity.java, src/main/java/com/playground/api/vote/entity/QestnAnswerPK.java, src/main/java/com/playground/api/vote/entity/QestnEntity.java, src/main/java/com/playground/api/vote/entity/QestnPK.java, src/main/java/com/playground/api/vote/entity/VoteEntity.java, src/main/java/com/playground/api/vote/entity/VoteIemEntity.java, src/main/java/com/playground/api/vote/entity/VoteIemPK.java, src/main/java/com/playground/api/vote/model/QestnAnswerRequest.java, src/main/java/com/playground/api/vote/model/QestnAnswerResponse.java, src/main/java/com/playground/api/vote/model/QestnRequest.java, src/main/java/com/playground/api/vote/model/QestnResponse.java, src/main/java/com/playground/api/vote/model/VoteIemRequest.java, src/main/java/com/playground/api/vote/model/VoteIemResponse.java, src/main/java/com/playground/api/vote/model/VoteRequest.java, src/main/java/com/playground/api/vote/model/VoteResponse.java, src/main/java/com/playground/api/vote/repository/VoteRepository.java, src/main/java/com/playground/api/vote/service/VoteService.java
[PLAYG-40--API] second commit and push
=> [PLAYG-40--API] second commit and push

src/main/java/com/playground/config/SwaggerConfig.java
swagger 우측 상단 group영역 샘플 api group 추가
=> PLAYG-50-Swagger-Config-샘플group추가

src/main/java/com/playground/api/vote/controller/QestnIemController.java, src/main/java/com/playground/api/vote/model/VoteIemResponse.java, src/main/java/com/playground/api/vote/model/VoteResponse.java, src/main/java/com/playground/api/vote/repository/QestnRepository.java, src/main/java/com/playground/api/vote/repository/VoteRepository.java, src/main/java/com/playground/api/vote/repository/dsl/VoteRepositoryCustom.java, src/main/java/com/playground/api/vote/repository/dsl/VoteRepositoryImpl.java, src/main/java/com/playground/api/vote/service/QestnIemService.java, src/main/java/com/playground/api/vote/service/VoteService.java
PLAYG-40 투표 delete 와 update 기능 개발
=> PLAYG-40--API-20240508

src/main/java/com/playground/api/member/service/MberService.java, src/main/java/com/playground/utils/JwtTokenUtil.java
jwtUtil getUsernameFromToken 관련 수정, 내 정보 조회 @Cacheable 수정
=> PLAYG-54-내-정보-조회

src/main/java/com/playground/api/vote/controller/AnswerController.java, src/main/java/com/playground/api/vote/controller/QestnIemController.java, src/main/java/com/playground/api/vote/entity/QestnAnswerEntity.java, src/main/java/com/playground/api/vote/repository/QestnAnswerRepository.java, src/main/java/com/playground/api/vote/repository/dsl/QestnAnswerRepositoryCustom.java, src/main/java/com/playground/api/vote/repository/dsl/QestnAnswerRepositoryImpl.java, src/main/java/com/playground/api/vote/service/AnswerService.java
사용자가 투표 할 때 사용 되는 api 개발, 투표 조회 등록 수정 삭제
=> PLAYG-53--API-UserVoting

src/main/java/com/playground/api/sample/repository/redis/RedisRepository.java, src/main/java/com/playground/api/sample/service/RedisService.java, src/main/java/com/playground/config/RedisConfig.java, src/main/java/com/playground/config/RoutingDataSourceConfig.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/application.yml
JPA에서 Redis Repostory, Redis에서 JPA Repostory를 scan하지 않기 위해 base package 설정
=> PLAYG-61-JPA-Redis-basePackage-설정

src/main/java/com/playground/api/notice/controller/CommentController.java, src/main/java/com/playground/api/notice/controller/PostController.java, src/main/java/com/playground/api/notice/entity/CommentEntity.java, src/main/java/com/playground/api/notice/entity/CommentEntityPK.java, src/main/java/com/playground/api/notice/entity/NoticeEntity.java, src/main/java/com/playground/api/notice/entity/PostEntity.java, src/main/java/com/playground/api/notice/entity/PostEntityPK.java, src/main/java/com/playground/api/notice/model/CommentRequest.java, src/main/java/com/playground/api/notice/model/CommentResponse.java, src/main/java/com/playground/api/notice/model/NoticeRequest.java, src/main/java/com/playground/api/notice/model/NoticeResponse.java, src/main/java/com/playground/api/notice/model/PostRequest.java, src/main/java/com/playground/api/notice/model/PostResponse.java, src/main/java/com/playground/api/notice/repository/CommentRepository.java, src/main/java/com/playground/api/notice/repository/PostRepository.java, src/main/java/com/playground/api/notice/service/CommentService.java, src/main/java/com/playground/api/notice/service/NoticeService.java, src/main/java/com/playground/api/notice/service/PostService.java
PLAYG-64-NOTICE entity, request, response명 update
=> PLAYG-64-NOTICE-CRUD-API

README.md, src/main/java/com/playground/api/comment/controller/CommentController.java, src/main/java/com/playground/api/comment/entity/CommentEntity.java, src/main/java/com/playground/api/comment/entity/CommentEntityPK.java, src/main/java/com/playground/api/comment/model/CommentRequest.java, src/main/java/com/playground/api/comment/model/CommentResponse.java, src/main/java/com/playground/api/comment/repository/CommentRepository.java, src/main/java/com/playground/api/comment/service/CommentService.java, src/main/java/com/playground/api/restaurant/entity/RstrntMenuHashtagMapngEntity.java, src/main/java/com/playground/api/restaurant/entity/RstrntMenuHashtagMapngPK.java, src/main/java/com/playground/api/restaurant/model/RstrntMenuAddRequest.java, src/main/java/com/playground/api/restaurant/repository/RstrntMenuHashtagMapngRepository.java, src/main/java/com/playground/api/restaurant/service/RstrntMenuService.java, src/main/java/com/playground/api/sample/model/SmpleResponse.java
=> PLAYG-52-Commnet-CRUD-API

src/main/java/com/playground/api/menu/controller/MenuController.java, src/main/java/com/playground/api/menu/model/SearchMenuRequest.java, src/main/java/com/playground/api/menu/service/MenuService.java
=> PLAYG-65-페이징처리API수정

src/main/java/com/playground/api/member/model/SignInResponse.java, src/main/java/com/playground/api/member/service/MberService.java
=> PLAYG-71-로그인-response-변경

src/main/java/com/playground/api/restaurant/service/RstrntService.java
식당 삭제 시 해당 식당 메뉴들도 함께 삭제될 수 있도록 수정
=> PLAYG-62-API-식당API수정

src/main/java/com/playground/api/hashtag/controller/HashtagController.java, src/main/java/com/playground/api/hashtag/model/HashtagSrchRequest.java, src/main/java/com/playground/api/hashtag/repository/HashtagRepository.java, src/main/java/com/playground/api/hashtag/repository/dsl/HashtagRepositoryCustom.java, src/main/java/com/playground/api/hashtag/repository/dsl/HashtagRepositoryImpl.java, src/main/java/com/playground/api/hashtag/service/HashtagService.java, src/main/java/com/playground/api/restaurant/controller/RstrntMenuHashtagController.java, src/main/java/com/playground/api/restaurant/entity/RstrntMenuEntity.java, src/main/java/com/playground/api/restaurant/entity/RstrntMenuHashtagMapngEntity.java, src/main/java/com/playground/api/restaurant/entity/RstrntMenuHashtagMapngPK.java, src/main/java/com/playground/api/restaurant/model/RstrntMenuHashtagAddRequest.java, src/main/java/com/playground/api/restaurant/model/RstrntMenuHashtagSrchRequest.java, src/main/java/com/playground/api/restaurant/repository/RstrntMenuRepository.java, src/main/java/com/playground/api/restaurant/repository/dsl/RstrntMenuRepositoryCustom.java, src/main/java/com/playground/api/restaurant/repository/dsl/RstrntMenuRepositoryImpl.java, src/main/java/com/playground/api/restaurant/service/RstrntMenuHashtagService.java, src/main/java/com/playground/api/restaurant/service/RstrntMenuService.java, src/main/java/com/playground/api/restaurant/service/RstrntService.java, src/main/java/com/playground/constants/HashtagType.java
=> PLAYG-63-메뉴해시태그-API

src/main/java/com/playground/api/code/controller/CodeController.java, src/main/java/com/playground/api/code/model/CodeGroupSrchRequest.java, src/main/java/com/playground/api/code/model/CodeSrchRequest.java, src/main/java/com/playground/api/code/model/CodeSrchResponse.java, src/main/java/com/playground/api/code/repository/CodeRepository.java, src/main/java/com/playground/api/code/service/CodeService.java, src/main/java/com/playground/api/member/service/MberService.java, src/main/java/com/playground/config/CacheConfig.java
=> PLAYG-90-코드조회-api-추가

src/main/java/com/playground/api/menu/controller/MenuController.java, src/main/java/com/playground/api/menu/repository/MenuRepository.java, src/main/java/com/playground/api/menu/repository/dsl/MenuRepositoryCustom.java, src/main/java/com/playground/api/menu/repository/dsl/MenuRepositoryImpl.java, src/main/java/com/playground/api/menu/service/MenuService.java
=> PLAYG-96-API-권한관리메뉴조회API수정

src/main/java/com/playground/api/menu/repository/dsl/MenuRepositoryImpl.java
메뉴 조회 시 기본권한에 매핑된 메뉴도 같이 조회되도록 수정
=> PLAYG-107--API-메뉴조회API수정

src/main/java/com/playground/api/menu/controller/MenuController.java, src/main/java/com/playground/api/menu/model/MenuRequest.java, src/main/java/com/playground/api/menu/repository/MenuRepository.java, src/main/java/com/playground/api/menu/repository/dsl/MenuRepositoryCustom.java, src/main/java/com/playground/api/menu/repository/dsl/MenuRepositoryImpl.java, src/main/java/com/playground/api/menu/service/MenuService.java
=> PLAYG-111--CRUD-메뉴관리CRUD수정

src/main/java/com/playground/api/menu/controller/MenuController.java, src/main/java/com/playground/api/menu/model/MenuRequest.java, src/main/java/com/playground/api/menu/service/MenuService.java
=> PLAYG-111 사용여부 변경 수정

src/main/java/com/playground/api/ai/service/EmbeddingService.java, src/main/java/com/playground/api/code/model/CodeSrchRequest.java, src/main/java/com/playground/api/common/service/impl/RestPageImpl.java, src/main/java/com/playground/api/hashtag/repository/dsl/HashtagRepositoryImpl.java, src/main/java/com/playground/api/restaurant/controller/RstrntController.java, src/main/java/com/playground/api/restaurant/model/RstrntModifyImageRequest.java, src/main/java/com/playground/api/restaurant/repository/dsl/RstrntMenuRepositoryImpl.java, src/main/java/com/playground/api/restaurant/repository/dsl/RstrntRepositoryCustom.java, src/main/java/com/playground/api/restaurant/repository/dsl/RstrntRepositoryImpl.java, src/main/java/com/playground/api/restaurant/service/RstrntMenuHashtagService.java, src/main/java/com/playground/api/restaurant/service/RstrntMenuService.java, src/main/java/com/playground/api/restaurant/service/RstrntService.java
embedding 코드로 조회 여부 수정
페이징처리된 list 캐싱을 위한 RestPageImpl 추가
식당, 메뉴, 해시태그 관련 api 수정
=> PLAYG-86-식당-메뉴-해시태그-api

src/main/java/com/playground/api/code/controller/CodeController.java, src/main/java/com/playground/api/code/model/CodeAddRequest.java, src/main/java/com/playground/api/code/model/CodeRemoveRequest.java, src/main/java/com/playground/api/code/model/CodeSearchRequest.java, src/main/java/com/playground/api/code/repository/CodeRepository.java, src/main/java/com/playground/api/code/repository/dsl/CodeRepositoryCustom.java, src/main/java/com/playground/api/code/repository/dsl/CodeRepositoryImpl.java, src/main/java/com/playground/api/code/service/CodeService.java
=> PLAYG-115-CodeAPI수정

src/main/java/com/playground/api/restaurant/entity/RstrntEntity.java, src/main/java/com/playground/api/restaurant/entity/RstrntMenuEntity.java, src/main/java/com/playground/api/restaurant/repository/dsl/RstrntRepositoryImpl.java, src/main/java/com/playground/api/restaurant/service/RstrntService.java
식당 테이블 구조 변경으로 인한 entity 및 API 수정
=> PLAYG-128-식당테이블구조변경

src/main/java/com/playground/api/restaurant/controller/RstrntController.java, src/main/java/com/playground/api/restaurant/entity/RstrntEntity.java, src/main/java/com/playground/api/restaurant/entity/RstrntFileEntity.java, src/main/java/com/playground/api/restaurant/model/RstrntAddRequest.java, src/main/java/com/playground/api/restaurant/model/RstrntFileResponse.java, src/main/java/com/playground/api/restaurant/model/RstrntRemoveRequest.java, src/main/java/com/playground/api/restaurant/model/RstrntSrchRequest.java, src/main/java/com/playground/api/restaurant/model/RstrntSrchResponse.java, src/main/java/com/playground/api/restaurant/repository/RstrntFileRepository.java, src/main/java/com/playground/api/restaurant/repository/dsl/RstrntFileRepositoryCustom.java, src/main/java/com/playground/api/restaurant/repository/dsl/RstrntFileRepositoryImpl.java, src/main/java/com/playground/api/restaurant/repository/dsl/RstrntRepositoryImpl.java, src/main/java/com/playground/api/restaurant/service/RstrntService.java
=> 식당 목록 조회, 상세 조회 api 수정

src/main/java/com/playground/api/eventuser/controller/EventUserController.java, src/main/java/com/playground/api/eventuser/model/EventUserDetailRequest.java, src/main/java/com/playground/api/eventuser/model/EventUserDetailResponse.java, src/main/java/com/playground/api/eventuser/model/EventUserListRequest.java, src/main/java/com/playground/api/eventuser/model/EventUserListResponse.java, src/main/java/com/playground/api/eventuser/model/PointPaymentResponse.java, src/main/java/com/playground/api/eventuser/repository/EventUserRepository.java, src/main/java/com/playground/api/eventuser/repository/dsl/EventUserRepositoryCustom.java, src/main/java/com/playground/api/eventuser/repository/dsl/EventUserRepositoryImpl.java, src/main/java/com/playground/api/eventuser/service/EventUserService.java
=> PLAYG-153-사용자-이벤트-상세-조회

src/main/java/com/playground/api/vote/controller/VoteController.java, src/main/java/com/playground/api/vote/model/VoteSrchRequest.java, src/main/java/com/playground/api/vote/model/VoteSrchResponse.java, src/main/java/com/playground/api/vote/repository/dsl/VoteRepositoryCustom.java, src/main/java/com/playground/api/vote/repository/dsl/VoteRepositoryImpl.java, src/main/java/com/playground/api/vote/service/VoteService.java
=> PLAYG-132-투표목록조회API

src/main/java/com/playground/api/vote/model/VoteAddRequest.java, src/main/java/com/playground/api/vote/model/VoteSrchRequest.java, src/main/java/com/playground/api/vote/model/VoteSrchResponse.java, src/main/java/com/playground/api/vote/repository/dsl/VoteRepositoryCustom.java, src/main/java/com/playground/api/vote/repository/dsl/VoteRepositoryImpl.java, src/main/java/com/playground/api/vote/service/VoteService.java
사용자조회시 답변여부도 함께 조회 될 수 있도록 API변경
=> PLAYG-132-식당목록조회API수정
